# Neural Network in Numpy

Below is the class to initialize our Neural Network with given input, output and hidden layer size.

In [1]:
class Neural_Network (object):
    def __init__(self,i,j,k):
        #define hyperparameters
        self.inputLayerSize = i
        self.outputLayerSize = j
        self.hiddenLayerSize = k

        #randomly initialize weights according to input, hidden and output layer size
        self.W1 = np.random.rand(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.rand(self.hiddenLayerSize,self.outputLayerSize)

    def forward(self,X):
        # A forward function that calculates output of the network with given input data
        self.z2 = np.dot(X,self.W1)
        self.a2 = self.sigmoid(self.z2) #An activation function defined below
        self.z3 = np.dot(self.a2,self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat

    def sigmoid(self,z):
        #sigmoid activation function to intoduce non-linearity
        return 1/(1+np.exp(-z))

    def sigmoidprime(self,z):
        # Derivative of sigmoid function, this will be used to while backpropagating the error during Gradient Descent
        return np.exp(-z)/(1+np.exp(-z)**2)

    def costFunction (self,X,y):
        #Calculate error
        self.yHat = self.forward(X)
        return 1/2*sum((y-self.yHat)**2)

    def costFunctionPrime (self,X,y):
        # Calculate derivative of error with respect to each weight, I recommend to refer the math behind below calculations         
        self.yHat = self.forward(X)

        delta3 = np.multiply(-(y - self.yHat),self.sigmoidprime(self.z3))
        dJdW2 = np.dot(self.a2.T,delta3) #Change in error with respect to change in W2

        delta2 = np.dot(delta3,self.W2.T)*self.sigmoidprime(self.z2)
        dJdW1 = np.dot(X.T,delta2) #Change in error with respect to change in W1 

        return dJdW1,dJdW2


#### Define input and out for an OR gate

In [4]:
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

#### Lets see, how network predicts before training

In [10]:
NeuralNet = Neural_Network(2,1,3)
NeuralNet.forward(X)

array([[0.63774381],
       [0.6690464 ],
       [0.66264521],
       [0.69010892]])

Above output is nowhere close to an acutal OR gate output (0,1,1,1). Lets see how it performs after training it for 1000 epochs.

#### Define and Train out network on above input and output data

In [11]:
#Update the weights according to Gradient Descent.
for i in range(1000):
    djdw1,djdw2 = NeuralNet.costFunctionPrime(X,Y)
    NeuralNet.W1 = NeuralNet.W1 - 0.1*djdw1
    NeuralNet.W2 = NeuralNet.W2 - 0.1*djdw2

#### Make predictions

In [12]:
NeuralNet.forward([[0,0],[0,1],[1,0],[1,1]])

array([[0.35281643],
       [0.80104383],
       [0.81582241],
       [0.88897452]])

As we can see, the output has changed and it looks like network is learning something. Its getting closer to the desired output

#### Let's run it for few more epochs

In [13]:
#Update the weights according to Gradient Descent.
for i in range(10000):
    djdw1,djdw2 = NeuralNet.costFunctionPrime(X,Y)
    NeuralNet.W1 = NeuralNet.W1 - 0.1*djdw1
    NeuralNet.W2 = NeuralNet.W2 - 0.1*djdw2

In [14]:
NeuralNet.forward([[0,0],[0,1],[1,0],[1,1]])

array([[0.04052142],
       [0.97538506],
       [0.97534644],
       [0.98948055]])

#### Woah! It almost predicted perfect output!Similarly, we can fit any function given with proper training data and proper size of network.